stages:
- deploy

dev-deploy:
  stage: deploy
  script:
    - deploy.sh /home/www/dev gfit-home
  environment:
    name: develop
    url: https://dev.gfitgo.com
  only:
    - develop
  tags:
    - deploy

prod-deploy:
  stage: deploy
  script:
    - deploy.sh /home/www gfit-home
  environment:
    name: production
    url: https://g.gfitgo.com
  only:
    - master
  tags:
    - deploy